package advent2019.day20

val input = """
    
        Walk from AA to XF (16 steps)
        Recurse into level 1 through XF (1 step)
        Walk from XF to CK (10 steps)
        Recurse into level 2 through CK (1 step)
        Walk from CK to ZH (14 steps)
        Recurse into level 3 through ZH (1 step)
        Walk from ZH to WB (10 steps)
        Recurse into level 4 through WB (1 step)
        Walk from WB to IC (10 steps)
        Recurse into level 5 through IC (1 step)
        Walk from IC to RF (10 steps)
        Recurse into level 6 through RF (1 step)
        Walk from RF to NM (8 steps)
        Recurse into level 7 through NM (1 step)
        Walk from NM to LP (12 steps)
        Recurse into level 8 through LP (1 step)
        Walk from LP to FD (24 steps)
        Recurse into level 9 through FD (1 step)
        Walk from FD to XQ (8 steps)
        Recurse into level 10 through XQ (1 step)
        Walk from XQ to WB (4 steps)
        Return to level 9 through WB (1 step)
        Walk from WB to ZH (10 steps)
        Return to level 8 through ZH (1 step)
        Walk from ZH to CK (14 steps)
        Return to level 7 through CK (1 step)
        Walk from CK to XF (10 steps)
        Return to level 6 through XF (1 step)
        Walk from XF to OA (14 steps)
        Return to level 5 through OA (1 step)
        Walk from OA to CJ (8 steps)
        Return to level 4 through CJ (1 step)
        Walk from CJ to RE (8 steps)
        Return to level 3 through RE (1 step)
        Walk from RE to IC (4 steps)
        Recurse into level 4 through IC (1 step)
        Walk from IC to RF (10 steps)
        Recurse into level 5 through RF (1 step)
        Walk from RF to NM (8 steps)
        Recurse into level 6 through NM (1 step)
        Walk from NM to LP (12 steps)
        Recurse into level 7 through LP (1 step)
        Walk from LP to FD (24 steps)
        Recurse into level 8 through FD (1 step)
        Walk from FD to XQ (8 steps)
        Recurse into level 9 through XQ (1 step)
        Walk from XQ to WB (4 steps)
        Return to level 8 through WB (1 step)
        Walk from WB to ZH (10 steps)
        Return to level 7 through ZH (1 step)
        Walk from ZH to CK (14 steps)
        Return to level 6 through CK (1 step)
        Walk from CK to XF (10 steps)
        Return to level 5 through XF (1 step)
        Walk from XF to OA (14 steps)
        Return to level 4 through OA (1 step)
        Walk from OA to CJ (8 steps)
        Return to level 3 through CJ (1 step)
        Walk from CJ to RE (8 steps)
        Return to level 2 through RE (1 step)
        Walk from RE to XQ (14 steps)
        Return to level 1 through XQ (1 step)
        Walk from XQ to FD (8 steps)
        Return to level 0 through FD (1 step)
        Walk from FD to ZZ (18 steps)

""".trimIndent().lines().filter { it.isNotBlank() }

val regex1 = Regex(".*Walk from (..) to (..).*")
val regex2 = Regex(".*(Return to|Recurse into).* through (..).*")

fun main() {
    input.map {
        val match1 = regex1.matchEntire(it)
        val match2 = regex2.matchEntire(it)
        match1?.destructured?.component2() ?: match2!!.destructured.component2()
    }
        .reversed()
        .also { println(it) }

}